[package]
name = "platform_signin"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.6"
jsonwebtoken = "^7"
time = "0.3.5"
serde = "1.0.130"
serde_json = "1.0.72"
